apiVersion: v2
# StackStorm version which refers to Docker images tag
appVersion: "3.8"
name: stackstorm-ha
version: 1.0.0-pw-0.4
description: StackStorm K8s Helm Chart, optimized for running StackStorm in HA environment.
home: https://stackstorm.com/
icon: https://landscape.cncf.io/logos/stack-storm.svg
source:
  - https://github.com/stackstorm/stackstorm-k8s
keywords:
  - st2
  - stackstorm
  - devops
  - SRE
  - automation
  - chatops
  - event-driven
  - auto-remediation
  - IFTTT
  - HA
maintainers:
  - name: The StackStorm Authors
    email: info@stackstorm.com
    url: https://github.com/StackStorm
details:
  This Helm chart is a fully installable app that codifies StackStorm cluster deployment optimized for HA and K8s environment.
  RabbitMQ-HA, MongoDB-HA clusters and Redis coordination backend st2 relies on will be deployed as 3rd party chart dependencies.
  For configuration details please check default values.yaml and README.
dependencies:
  - name: rabbitmq
    version: 8.0.2
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: rabbitmq.enabled
  - name: mongodb
    version: 10.0.1
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: mongodb.enabled
  - name: external-dns
    version: 4.0.0
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: external-dns.enabled
  - name: redis
    version: 17.3.11
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: zookeeper
    # We can't use a version higher than 10.2.5 because of the following issue: This major version removes commonAnnotations and commonLabels from volumeClaimTemplates. Now annotations and labels can be set in volume claims using persistence.annotations and persistence.labels values. If the previous deployment has already set commonAnnotations and/or commonLabels values, to ensure a clean upgrade from previous version without loosing data, please set persistence.annotations and/or persistence.labels values with the same content as the common values.
    # The use of bitnami common chart 2.x.x conflicts with other bitnami charts here
    version: 10.2.5
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled